---
# inventory/hosts.yml
# @version v1.00_2021-NOV-14
# @author Kevin Jeffery

all:
  hosts:
    ansible.sample.com: # Ansible Control Node Alma Linux 8.3

  children:
    ansible:
      hosts:
        ansible.sample.com: # Ansible Control Node Alma Linux 8.3

  vars:
