---
# playbooks/ansible_isam.yml
# @version v2.00_2021-NOV-14
# @author Kevin Jeffery

- name: Build the Ansible Control system for ISAM
  hosts:
    ansible

  tasks:
  - name: Set authorized key
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Install Ansible dependencies - Linux 8
    dnf:
      name: "{{ ansible_packages }}"
      state: "latest"
      update_cache: "yes"
    become: "yes"
    when:
      - ansible_packages is defined
      - ansible_distribution in ['RedHat','CentOS', 'Rocky', 'AlmaLinux']
      - ansible_distribution_version is version('8.0', 'ge')
 
  - name: Ensure latest version of pip
    pip:
      name: "pip"
      state: "latest"
    become: yes
 
  - name: Install IBM-Security python library and pre-requisites
    pip:
      name:
      - "requests"
      # - "importlib" # Not required for Python3 - built in.
      - "git+https://github.com/ibm-security/ibmsecurity#egg=ibmsecurity"
      state: "latest"
    become: yes
 
  # - name: Install/Update ISAM Ansible Roles
  #   command: ansible-galaxy install git+https://github.com/ibm-security/isam-ansible-roles.git,master --roles-path {{ isam_roles_path | quote }} --force
  #   when: isam_roles_path is defined

  - name: Install/Update ibm.isam Ansible Collection
    command: ansible-galaxy collection install ibm.isam --force
